Repository Learnathon-By-Geeky-Solutions/byte-breeze, pull requests merged in 2025-04, with the labels that each got.

#258 Feat/main sd 28 rider view all parcel delivery history
  src/main/java/com/bytebreeze/quickdrop/controller/RiderController.java
  src/main/java/com/bytebreeze/quickdrop/repository/ParcelRepository.java
  src/main/java/com/bytebreeze/quickdrop/service/ParcelService.java
  src/main/resources/templates/fragments/sidebar-rider.html
  src/main/resources/templates/master-layout-rider.html
  src/main/resources/templates/rider/view-history.html
Labels: feature

#262 sync develop with main branch
  build.gradle
  src/main/java/com/bytebreeze/quickdrop/controller/RiderController.java
  src/main/java/com/bytebreeze/quickdrop/repository/ParcelRepository.java
  src/main/java/com/bytebreeze/quickdrop/service/ParcelService.java
  src/main/java/com/bytebreeze/quickdrop/service/RiderService.java
  src/main/resources/templates/fragments/sidebar-rider.html
  src/main/resources/templates/master-layout-rider.html
  src/main/resources/templates/rider/view-history.html
Labels: Pull Request

#264 Resolve security hotspots and reliability issues
  src/main/java/com/bytebreeze/quickdrop/controller/FileController.java
  src/main/java/com/bytebreeze/quickdrop/security/SecurityConfig.java
  src/main/java/com/bytebreeze/quickdrop/service/FileStorageService.java
  src/main/java/com/bytebreeze/quickdrop/service/ParcelService.java
  src/main/java/com/bytebreeze/quickdrop/service/SSLCommerzPaymentService.java
Labels: Pull Request

#275 Add unit test for service layer
  src/main/java/com/bytebreeze/quickdrop/exception/custom/FileStorageException.java
  src/main/java/com/bytebreeze/quickdrop/service/FileStorageService.java
  src/main/java/com/bytebreeze/quickdrop/service/RiderService.java
  src/main/java/com/bytebreeze/quickdrop/service/SSLCommerzPaymentService.java
  src/test/java/com/bytebreeze/quickdrop/service/FileStorageServiceTest.java
  src/test/java/com/bytebreeze/quickdrop/service/ParcelServiceTest.java
  src/test/java/com/bytebreeze/quickdrop/service/RiderServiceTest.java
  src/test/java/com/bytebreeze/quickdrop/service/SSLCommerzPaymentServiceTest.java
  src/test/java/com/bytebreeze/quickdrop/service/UserServiceTest.java
  src/test/resources/test-files/sample.pdf
Labels: bug, feature, Pull Request

#286 Write unit test for AuthUtil and SSLCommerzUtil
  src/main/java/com/bytebreeze/quickdrop/util/SSLCommerzUtil.java
  src/test/java/com/bytebreeze/quickdrop/util/AuthUtilTest.java
  src/test/java/com/bytebreeze/quickdrop/util/SSLCommerzUtilTest.java
Labels: feature

#287 Write unit test for AuthUtil and SSLCommerzUtil
  src/main/java/com/bytebreeze/quickdrop/util/SSLCommerzUtil.java
  src/test/java/com/bytebreeze/quickdrop/util/AuthUtilTest.java
  src/test/java/com/bytebreeze/quickdrop/util/SSLCommerzUtilTest.java
Labels: feature

#299 Refactor codebase for reduce cognitive complexity
  build.gradle
  src/main/java/com/bytebreeze/quickdrop/config/ModelMapperConfig.java
  src/main/java/com/bytebreeze/quickdrop/service/HashVerificationService.java
  src/main/java/com/bytebreeze/quickdrop/service/ParcelService.java
  src/main/java/com/bytebreeze/quickdrop/service/SSLCommerzPaymentService.java
  src/main/java/com/bytebreeze/quickdrop/service/UserService.java
  src/test/java/com/bytebreeze/quickdrop/service/HashVerificationServiceTest.java
  src/test/java/com/bytebreeze/quickdrop/service/ParcelServiceTest.java
  src/test/java/com/bytebreeze/quickdrop/service/SSLCommerzPaymentServiceTest.java
  src/test/java/com/bytebreeze/quickdrop/service/UserServiceTest.java
Labels: enhancement

#303 Configure micrometer and opentelemetry for observeability feature
  build.gradle
  src/main/java/com/bytebreeze/quickdrop/config/OtlpConfiguration.java
  src/main/resources/application.properties
Labels: feature

#307 Refactor codebase
  src/main/java/com/bytebreeze/quickdrop/controller/AdminController.java
  src/main/java/com/bytebreeze/quickdrop/controller/AuthController.java
  src/main/java/com/bytebreeze/quickdrop/controller/FileController.java
  src/main/java/com/bytebreeze/quickdrop/controller/ParcelShippingCostController.java
  src/main/java/com/bytebreeze/quickdrop/controller/RiderController.java
  src/main/java/com/bytebreeze/quickdrop/controller/SSLCommerzPaymentApiController.java
  src/main/java/com/bytebreeze/quickdrop/controller/UserController.java
  src/main/java/com/bytebreeze/quickdrop/dto/request/RiderOnboardingDTO.java
  src/main/java/com/bytebreeze/quickdrop/dto/request/RiderRegistrationRequestDTO.java
  src/main/java/com/bytebreeze/quickdrop/dto/request/UserProfileUpdateDto.java
  src/main/java/com/bytebreeze/quickdrop/dto/request/UserRegistrationRequestDTO.java
  src/main/java/com/bytebreeze/quickdrop/dto/response/RiderDashboardResponseDTO.java
  src/main/java/com/bytebreeze/quickdrop/entity/ParcelEntity.java
  src/main/java/com/bytebreeze/quickdrop/entity/PaymentEntity.java
  src/main/java/com/bytebreeze/quickdrop/entity/ProductCategoryEntity.java
  src/main/java/com/bytebreeze/quickdrop/entity/RiderEntity.java
  src/main/java/com/bytebreeze/quickdrop/entity/UserEntity.java
  src/main/java/com/bytebreeze/quickdrop/exception/AlreadyExistsException.java
  src/main/java/com/bytebreeze/quickdrop/exception/FileStorageException.java
  src/main/java/com/bytebreeze/quickdrop/exception/FileValidationException.java
  src/main/java/com/bytebreeze/quickdrop/exception/ParcelAlreadyAssignedException.java
  src/main/java/com/bytebreeze/quickdrop/exception/ParcelNotFoundException.java
  src/main/java/com/bytebreeze/quickdrop/exception/SSLCommerzPaymentInitializationException.java
  src/main/java/com/bytebreeze/quickdrop/exception/UserNotFoundException.java
  src/main/java/com/bytebreeze/quickdrop/mapper/OnboardRiderMapper.java
  src/main/java/com/bytebreeze/quickdrop/mapper/RegisterRiderMapper.java
  src/main/java/com/bytebreeze/quickdrop/repository/ParcelRepository.java
  src/main/java/com/bytebreeze/quickdrop/repository/PaymentRepository.java
  src/main/java/com/bytebreeze/quickdrop/repository/ProductCategoryRepository.java
  src/main/java/com/bytebreeze/quickdrop/repository/RiderRepository.java
  src/main/java/com/bytebreeze/quickdrop/repository/UserRepository.java
  src/main/java/com/bytebreeze/quickdrop/security/CustomUserDetailsService.java
  src/main/java/com/bytebreeze/quickdrop/service/FileStorageService.java
  src/main/java/com/bytebreeze/quickdrop/service/ParcelService.java
  src/main/java/com/bytebreeze/quickdrop/service/PaymentService.java
  src/main/java/com/bytebreeze/quickdrop/service/ProductCategoryService.java
  src/main/java/com/bytebreeze/quickdrop/service/RiderService.java
  src/main/java/com/bytebreeze/quickdrop/service/SSLCommerzPaymentService.java
  src/main/java/com/bytebreeze/quickdrop/service/UserService.java
  src/main/java/com/bytebreeze/quickdrop/util/ProfileSettingUtil.java
  src/test/java/com/bytebreeze/quickdrop/controller/AdminControllerTest.java
  src/test/java/com/bytebreeze/quickdrop/controller/AuthControllerTest.java
  src/test/java/com/bytebreeze/quickdrop/controller/FileControllerTest.java
  src/test/java/com/bytebreeze/quickdrop/controller/RiderControllerTest.java
  src/test/java/com/bytebreeze/quickdrop/service/FileStorageServiceTest.java
  src/test/java/com/bytebreeze/quickdrop/service/HashVerificationServiceTest.java
  src/test/java/com/bytebreeze/quickdrop/service/ParcelServiceTest.java
  src/test/java/com/bytebreeze/quickdrop/service/ProductCategoryServiceTest.java
  src/test/java/com/bytebreeze/quickdrop/service/RiderServiceTest.java
  src/test/java/com/bytebreeze/quickdrop/service/SSLCommerzPaymentServiceTest.java
  src/test/java/com/bytebreeze/quickdrop/service/UserServiceTest.java
  src/test/java/com/bytebreeze/quickdrop/util/AuthUtilTest.java
  src/test/java/com/bytebreeze/quickdrop/util/ProfileSettingUtilTest.java
  src/test/java/com/bytebreeze/quickdrop/util/SSLCommerzUtilTest.java
Labels: feature, Pull Request, refactor

#309 Refactor Codebase
  src/main/java/com/bytebreeze/quickdrop/controller/AdminController.java
  src/main/java/com/bytebreeze/quickdrop/controller/AuthController.java
  src/main/java/com/bytebreeze/quickdrop/controller/FileController.java
  src/main/java/com/bytebreeze/quickdrop/controller/ParcelShippingCostController.java
  src/main/java/com/bytebreeze/quickdrop/controller/RiderController.java
  src/main/java/com/bytebreeze/quickdrop/controller/SSLCommerzPaymentApiController.java
  src/main/java/com/bytebreeze/quickdrop/controller/UserController.java
  src/main/java/com/bytebreeze/quickdrop/dto/request/RiderOnboardingDTO.java
  src/main/java/com/bytebreeze/quickdrop/dto/request/RiderRegistrationRequestDTO.java
  src/main/java/com/bytebreeze/quickdrop/dto/request/UserProfileUpdateDto.java
  src/main/java/com/bytebreeze/quickdrop/dto/request/UserRegistrationRequestDTO.java
  src/main/java/com/bytebreeze/quickdrop/dto/response/RiderDashboardResponseDTO.java
  src/main/java/com/bytebreeze/quickdrop/entity/ParcelEntity.java
  src/main/java/com/bytebreeze/quickdrop/entity/PaymentEntity.java
  src/main/java/com/bytebreeze/quickdrop/entity/ProductCategoryEntity.java
  src/main/java/com/bytebreeze/quickdrop/entity/RiderEntity.java
  src/main/java/com/bytebreeze/quickdrop/entity/UserEntity.java
  src/main/java/com/bytebreeze/quickdrop/exception/AlreadyExistsException.java
  src/main/java/com/bytebreeze/quickdrop/exception/FileStorageException.java
  src/main/java/com/bytebreeze/quickdrop/exception/FileValidationException.java
  src/main/java/com/bytebreeze/quickdrop/exception/ParcelAlreadyAssignedException.java
  src/main/java/com/bytebreeze/quickdrop/exception/ParcelNotFoundException.java
  src/main/java/com/bytebreeze/quickdrop/exception/SSLCommerzPaymentInitializationException.java
  src/main/java/com/bytebreeze/quickdrop/exception/UserNotFoundException.java
  src/main/java/com/bytebreeze/quickdrop/mapper/OnboardRiderMapper.java
  src/main/java/com/bytebreeze/quickdrop/mapper/RegisterRiderMapper.java
  src/main/java/com/bytebreeze/quickdrop/repository/ParcelRepository.java
  src/main/java/com/bytebreeze/quickdrop/repository/PaymentRepository.java
  src/main/java/com/bytebreeze/quickdrop/repository/ProductCategoryRepository.java
  src/main/java/com/bytebreeze/quickdrop/repository/RiderRepository.java
  src/main/java/com/bytebreeze/quickdrop/repository/UserRepository.java
  src/main/java/com/bytebreeze/quickdrop/security/CustomUserDetailsService.java
  src/main/java/com/bytebreeze/quickdrop/service/FileStorageService.java
  src/main/java/com/bytebreeze/quickdrop/service/ParcelService.java
  src/main/java/com/bytebreeze/quickdrop/service/PaymentService.java
  src/main/java/com/bytebreeze/quickdrop/service/ProductCategoryService.java
  src/main/java/com/bytebreeze/quickdrop/service/RiderService.java
  src/main/java/com/bytebreeze/quickdrop/service/SSLCommerzPaymentService.java
  src/main/java/com/bytebreeze/quickdrop/service/UserService.java
  src/main/java/com/bytebreeze/quickdrop/util/ProfileSettingUtil.java
  src/test/java/com/bytebreeze/quickdrop/controller/AdminControllerTest.java
  src/test/java/com/bytebreeze/quickdrop/controller/AuthControllerTest.java
  src/test/java/com/bytebreeze/quickdrop/controller/FileControllerTest.java
  src/test/java/com/bytebreeze/quickdrop/controller/RiderControllerTest.java
  src/test/java/com/bytebreeze/quickdrop/service/FileStorageServiceTest.java
  src/test/java/com/bytebreeze/quickdrop/service/HashVerificationServiceTest.java
  src/test/java/com/bytebreeze/quickdrop/service/ParcelServiceTest.java
  src/test/java/com/bytebreeze/quickdrop/service/ProductCategoryServiceTest.java
  src/test/java/com/bytebreeze/quickdrop/service/RiderServiceTest.java
  src/test/java/com/bytebreeze/quickdrop/service/SSLCommerzPaymentServiceTest.java
  src/test/java/com/bytebreeze/quickdrop/service/UserServiceTest.java
  src/test/java/com/bytebreeze/quickdrop/util/AuthUtilTest.java
  src/test/java/com/bytebreeze/quickdrop/util/ProfileSettingUtilTest.java
  src/test/java/com/bytebreeze/quickdrop/util/SSLCommerzUtilTest.java
Labels: feature, Pull Request, refactor

#317 Feature/main unit test for controller layer
  src/test/java/com/bytebreeze/quickdrop/controller/ParcelShippingCostControllerTest.java
  src/test/java/com/bytebreeze/quickdrop/controller/PublicControllerTest.java
  src/test/java/com/bytebreeze/quickdrop/controller/SSLCommerzPaymentApiControllerTest.java
  src/test/java/com/bytebreeze/quickdrop/controller/UserControllerTest.java
  src/test/java/com/bytebreeze/quickdrop/service/SSLCommerzPaymentServiceTest.java
Labels: feature

#322 Feat/main implement spring profiles
  src/main/resources/application-dev.properties
  src/main/resources/application-prod.properties
  src/main/resources/application.properties
  src/main/resources/db/migration/V6__Add_Initial_Parcel_Categories.sql
Labels: feature

#323 Introduce promethues and grafana for monitoring
  build.gradle
  src/main/resources/application.properties
Labels: enhancement

#327 Fix/main organize readme.md
  README.md
  docs/Team/UML/images/Main flow.png
  docs/Team/UML/images/Main flow1.png
  docs/Team/UML/images/Main flow3.png
  docs/Team/UML/images/Parcel_Delivery_Rider_logo.png
  docs/Team/UML/images/QuickDrop.jpg
  docs/Team/UML/images/deliveryparcel.me_.png
  docs/Team/UML/images/improved-delivery-system-svg.png
  docs/Team/UML/images/parcel-delivery-mvp-diagram.png
  docs/Team/UML/images/system-architecture-diagram.png
  docs/Team/UML/readme.md
Labels: enhancement

#329 Resolve flyway, file controller test, readme correction, private constructor related issuesTest/main file storage service test
  README.md
  src/main/java/com/bytebreeze/quickdrop/util/AuthUtil.java
  src/main/java/com/bytebreeze/quickdrop/util/ProfileSettingUtil.java
  src/main/resources/application.properties
  src/main/resources/db/migration/V7__Add_receiver_and_pickup_info_to_parcel_table.sql
  src/test/java/com/bytebreeze/quickdrop/QuickdropApplicationTests.java
  src/test/java/com/bytebreeze/quickdrop/controller/AdminControllerTest.java
  src/test/java/com/bytebreeze/quickdrop/controller/AuthControllerTest.java
  src/test/java/com/bytebreeze/quickdrop/controller/FileControllerTest.java
  src/test/java/com/bytebreeze/quickdrop/controller/ParcelShippingCostControllerTest.java
  src/test/java/com/bytebreeze/quickdrop/controller/PublicControllerTest.java
  src/test/java/com/bytebreeze/quickdrop/controller/RiderControllerTest.java
  src/test/java/com/bytebreeze/quickdrop/controller/SSLCommerzPaymentApiControllerTest.java
  src/test/java/com/bytebreeze/quickdrop/service/FileStorageServiceTest.java
  src/test/java/com/bytebreeze/quickdrop/service/HashVerificationServiceTest.java
  src/test/java/com/bytebreeze/quickdrop/service/ParcelServiceTest.java
  src/test/java/com/bytebreeze/quickdrop/service/ProductCategoryServiceTest.java
  src/test/java/com/bytebreeze/quickdrop/service/RiderServiceTest.java
  src/test/java/com/bytebreeze/quickdrop/service/SSLCommerzPaymentServiceTest.java
  src/test/java/com/bytebreeze/quickdrop/service/UserServiceTest.java
  src/test/java/com/bytebreeze/quickdrop/util/AuthUtilTest.java
  src/test/java/com/bytebreeze/quickdrop/util/ProfileSettingUtilTest.java
  src/test/java/com/bytebreeze/quickdrop/util/SSLCommerzUtilTest.java
Labels: enhancement

#330 Default admin creation using flyway implemented
  .gitignore
  src/main/java/com/bytebreeze/quickdrop/security/SecurityConfig.java
  src/main/resources/application.properties
  src/main/resources/db/migration/V8__Add_default_admin_account.sql
  src/main/resources/logback-spring.xml
  src/test/java/com/bytebreeze/quickdrop/controller/FileControllerTest.java
Labels: feature

#331 Fix security issue flagged by github code scan
  .github/workflows/spotless-check.yml
  .github/workflows/test-coverage.yml
  src/main/java/com/bytebreeze/quickdrop/service/FileStorageService.java
  src/main/resources/application.properties
  src/main/resources/static/images/auth-logo.png
  src/main/resources/static/js/intlTelInput.min.js
  src/main/resources/templates/admin/pending-riders.html
  src/main/resources/templates/auth/rider-register.html
  src/main/resources/templates/rider/view-current-parcels.html
  src/main/resources/templates/rider/view-history.html
Labels: Security Issue
