Repository Learnathon-By-Geeky-Solutions/byte-breeze, pull requests merged in 2025-03, with the labels that each got.

#203 Feat 02 01 cookie implementation
  src/main/java/com/bytebreeze/quickdrop/security/SecurityConfig.java
  src/main/resources/application.properties
  src/main/resources/templates/auth/admin-login.html
  src/main/resources/templates/auth/login.html
Labels: feature

#206 Login, Register and Landing page protected from logged in users.
  src/main/java/com/bytebreeze/quickdrop/controller/AdminController.java
  src/main/java/com/bytebreeze/quickdrop/controller/AuthController.java
  src/main/java/com/bytebreeze/quickdrop/controller/Dashboard.java
  src/main/java/com/bytebreeze/quickdrop/security/SecurityConfig.java
  src/main/java/com/bytebreeze/quickdrop/util/AuthUtil.java
Labels: bug, feature

#208 BUG : User/Admin redirection after successful signing out
  src/main/java/com/bytebreeze/quickdrop/security/SecurityConfig.java
  src/main/resources/templates/fragments/navbar-admin.html
  src/main/resources/templates/fragments/navbar.html
  src/main/resources/templates/fragments/sidebar-admin.html
  src/main/resources/templates/fragments/sidebar.html
Labels: bug

#210 Implement custom error page and user/admin redirection
  src/main/java/com/bytebreeze/quickdrop/controller/Dashboard.java
  src/main/java/com/bytebreeze/quickdrop/util/AuthUtil.java
  src/main/resources/templates/error.html
Labels: bug, enhancement, feature

#224 Bug/main sd 02 user login remember checkbox
  src/main/java/com/bytebreeze/quickdrop/security/SecurityConfig.java
  src/main/resources/templates/auth/login.html
  src/main/resources/templates/auth/rider-login.html
Labels: bug, feature, Pull Request

#225 Bug/main sd 11 rider onboarding bug
  src/main/java/com/bytebreeze/quickdrop/controller/RiderController.java
  src/main/java/com/bytebreeze/quickdrop/dto/RiderOnboardingDTO.java
  src/main/java/com/bytebreeze/quickdrop/repository/RiderRepository.java
  src/main/java/com/bytebreeze/quickdrop/service/FileStorageService.java
  src/main/java/com/bytebreeze/quickdrop/service/RiderService.java
  src/main/resources/templates/index.html
  src/main/resources/templates/rider/copyonboarding.html
  src/main/resources/templates/rider/onboarding.html
Labels: bug, Pull Request

#226 Main sd 05 sender book a parcel delivery request
  build.gradle
  src/main/java/com/bytebreeze/quickdrop/config/RestTemplateConfig.java
  src/main/java/com/bytebreeze/quickdrop/controller/UserController.java
  src/main/java/com/bytebreeze/quickdrop/controller/api/SSLCommerzPaymentApiController.java
  src/main/java/com/bytebreeze/quickdrop/dto/paymentapiresponse/SSLCommerzPaymentInitResponseDto.java
  src/main/java/com/bytebreeze/quickdrop/dto/paymentapiresponse/SSLCommerzValidatorResponse.java
  src/main/java/com/bytebreeze/quickdrop/dto/request/ParcelBookingRequestDTO.java
  src/main/java/com/bytebreeze/quickdrop/enums/ParcelStatus.java
  src/main/java/com/bytebreeze/quickdrop/enums/PaymentStatus.java
  src/main/java/com/bytebreeze/quickdrop/mapper/RegisterRiderMapper.java
  src/main/java/com/bytebreeze/quickdrop/model/Parcel.java
  src/main/java/com/bytebreeze/quickdrop/model/Payment.java
  src/main/java/com/bytebreeze/quickdrop/model/ProductCategory.java
  src/main/java/com/bytebreeze/quickdrop/model/Rider.java
  src/main/java/com/bytebreeze/quickdrop/model/User.java
  src/main/java/com/bytebreeze/quickdrop/repository/ParcelRepository.java
  src/main/java/com/bytebreeze/quickdrop/repository/PaymentRepository.java
  src/main/java/com/bytebreeze/quickdrop/repository/ProductCategoryRepository.java
  src/main/java/com/bytebreeze/quickdrop/service/ParcelService.java
  src/main/java/com/bytebreeze/quickdrop/service/PaymentService.java
  src/main/java/com/bytebreeze/quickdrop/service/ProductCategoryService.java
  src/main/java/com/bytebreeze/quickdrop/service/SSLCommerzPaymentService.java
  src/main/java/com/bytebreeze/quickdrop/util/AuthUtil.java
  src/main/java/com/bytebreeze/quickdrop/util/SSLCommerzUtil.java
  src/main/resources/application.properties
  src/main/resources/static/images/bkash_payment.png
  src/main/resources/static/images/rocket_payment.png
  src/main/resources/static/images/visa_payment.png
  src/main/resources/templates/dashboard/book-parcel.html
  src/main/resources/templates/dashboard/home.html
  src/main/resources/templates/fragments/field-error-fragment.html
  src/main/resources/templates/master-layout-user.html
  src/test/java/com/bytebreeze/quickdrop/service/ProductCategoryServiceTest.java
Labels: feature

#227 Main sd 05 sender book a parcel delivery request
  build.gradle
  src/main/java/com/bytebreeze/quickdrop/config/RestTemplateConfig.java
  src/main/java/com/bytebreeze/quickdrop/controller/UserController.java
  src/main/java/com/bytebreeze/quickdrop/controller/api/SSLCommerzPaymentApiController.java
  src/main/java/com/bytebreeze/quickdrop/dto/paymentapiresponse/SSLCommerzPaymentInitResponseDto.java
  src/main/java/com/bytebreeze/quickdrop/dto/paymentapiresponse/SSLCommerzValidatorResponse.java
  src/main/java/com/bytebreeze/quickdrop/dto/request/ParcelBookingRequestDTO.java
  src/main/java/com/bytebreeze/quickdrop/enums/ParcelStatus.java
  src/main/java/com/bytebreeze/quickdrop/enums/PaymentStatus.java
  src/main/java/com/bytebreeze/quickdrop/mapper/RegisterRiderMapper.java
  src/main/java/com/bytebreeze/quickdrop/model/Parcel.java
  src/main/java/com/bytebreeze/quickdrop/model/Payment.java
  src/main/java/com/bytebreeze/quickdrop/model/ProductCategory.java
  src/main/java/com/bytebreeze/quickdrop/model/Rider.java
  src/main/java/com/bytebreeze/quickdrop/model/User.java
  src/main/java/com/bytebreeze/quickdrop/repository/ParcelRepository.java
  src/main/java/com/bytebreeze/quickdrop/repository/PaymentRepository.java
  src/main/java/com/bytebreeze/quickdrop/repository/ProductCategoryRepository.java
  src/main/java/com/bytebreeze/quickdrop/service/ParcelService.java
  src/main/java/com/bytebreeze/quickdrop/service/PaymentService.java
  src/main/java/com/bytebreeze/quickdrop/service/ProductCategoryService.java
  src/main/java/com/bytebreeze/quickdrop/service/SSLCommerzPaymentService.java
  src/main/java/com/bytebreeze/quickdrop/util/AuthUtil.java
  src/main/java/com/bytebreeze/quickdrop/util/SSLCommerzUtil.java
  src/main/resources/application.properties
  src/main/resources/static/images/bkash_payment.png
  src/main/resources/static/images/rocket_payment.png
  src/main/resources/static/images/visa_payment.png
  src/main/resources/templates/dashboard/book-parcel.html
  src/main/resources/templates/dashboard/home.html
  src/main/resources/templates/fragments/field-error-fragment.html
  src/main/resources/templates/master-layout-user.html
  src/test/java/com/bytebreeze/quickdrop/service/ProductCategoryServiceTest.java
Labels: feature

#235 Feat/main sd 31 admin approve rider onboarding
  src/main/java/com/bytebreeze/quickdrop/controller/AdminController.java
  src/main/java/com/bytebreeze/quickdrop/controller/RiderController.java
  src/main/java/com/bytebreeze/quickdrop/dto/RiderDashboardResponseDTO.java
  src/main/java/com/bytebreeze/quickdrop/dto/response/RiderApprovalByAdminResponseDTO.java
  src/main/java/com/bytebreeze/quickdrop/mapper/OnboardRiderMapper.java
  src/main/java/com/bytebreeze/quickdrop/repository/RiderRepository.java
  src/main/java/com/bytebreeze/quickdrop/service/RiderService.java
  src/main/resources/templates/admin/pending-riders.html
  src/main/resources/templates/admin/previous-pending-riders.html
  src/main/resources/templates/fragments/sidebar-admin.html
Labels: feature

#244 Add new parcel status unpaid to resolve the bug
  src/main/java/com/bytebreeze/quickdrop/enums/ParcelStatus.java
  src/main/java/com/bytebreeze/quickdrop/model/Parcel.java
Labels: bug

#245 Improvement/main improvement 05 01 add pickup information
  src/main/java/com/bytebreeze/quickdrop/controller/SSLCommerzPaymentApiController.java
  src/main/java/com/bytebreeze/quickdrop/dto/request/ParcelBookingRequestDTO.java
  src/main/java/com/bytebreeze/quickdrop/model/Parcel.java
  src/main/java/com/bytebreeze/quickdrop/service/ParcelService.java
  src/main/resources/db/migration/V4__add_pickup_address_and_receiver_address_to_parcel.sql
  src/main/resources/static/css/jquery.dataTables.min.css
  src/main/resources/static/js/jquery-3.6.0.min.js
  src/main/resources/static/js/jquery.dataTables.min.js
  src/main/resources/templates/dashboard/book-parcel.html
  src/main/resources/templates/dashboard/parcel-history.html
Labels: enhancement

#247 Synchronize develop branch with main branch
  .github/workflows/test-coverage.yml
  LICENSE
  build.gradle
  sonar-project.properties
  src/main/java/com/bytebreeze/quickdrop/controller/SSLCommerzPaymentApiController.java
  src/main/java/com/bytebreeze/quickdrop/dto/request/ParcelBookingRequestDTO.java
  src/main/java/com/bytebreeze/quickdrop/enums/ParcelStatus.java
  src/main/java/com/bytebreeze/quickdrop/model/Parcel.java
  src/main/java/com/bytebreeze/quickdrop/service/ParcelService.java
  src/main/resources/application-test.properties
  src/main/resources/db/migration/V2__changed_rider_available_column.sql
  src/main/resources/db/migration/V3__changed_rider_available_column.sql
  src/main/resources/db/migration/V4__add_pickup_address_and_receiver_address_to_parcel.sql
  src/main/resources/static/css/jquery.dataTables.min.css
  src/main/resources/static/js/jquery-3.6.0.min.js
  src/main/resources/static/js/jquery.dataTables.min.js
  src/main/resources/templates/dashboard/book-parcel.html
  src/main/resources/templates/dashboard/parcel-history.html
  src/test/java/com/bytebreeze/quickdrop/QuickdropApplicationTests.java
Labels: Pull Request

#248 Feat/main sd 27 rider view all current parcel delivery request
  docs/Khairul/draftCode.java
  src/main/java/com/bytebreeze/quickdrop/controller/AdminController.java
  src/main/java/com/bytebreeze/quickdrop/controller/RiderController.java
  src/main/java/com/bytebreeze/quickdrop/dto/response/RiderViewCurrentParcelsResponseDTO.java
  src/main/java/com/bytebreeze/quickdrop/exception/custom/ParcelAlreadyAssignedException.java
  src/main/java/com/bytebreeze/quickdrop/exception/custom/ParcelNotFoundException.java
  src/main/java/com/bytebreeze/quickdrop/model/Rider.java
  src/main/java/com/bytebreeze/quickdrop/repository/ParcelRepository.java
  src/main/java/com/bytebreeze/quickdrop/service/RiderService.java
  src/main/resources/templates/dashboard/copy-rider-dashboard.html
  src/main/resources/templates/fragments/sidebar-rider.html
  src/main/resources/templates/rider/view-current-parcels.html
Labels: Pull Request

#250 Feat/main sd 32 admin can view rider onboarding details document
  src/main/java/com/bytebreeze/quickdrop/controller/AdminController.java
  src/main/java/com/bytebreeze/quickdrop/controller/FileController.java
  src/main/java/com/bytebreeze/quickdrop/dto/response/RiderDetailsResponseDto.java
  src/main/java/com/bytebreeze/quickdrop/service/RiderService.java
  src/main/resources/templates/admin/view-rider-details.html
  src/main/resources/templates/master-layout-admin.html
Labels: feature

#254 Feat/main sd 05 04 calculate estimated shipping cost
  src/main/java/com/bytebreeze/quickdrop/controller/ParcelShippingCostController.java
  src/main/java/com/bytebreeze/quickdrop/dto/request/CalculateShippingCostRequestDto.java
  src/main/java/com/bytebreeze/quickdrop/dto/request/ParcelBookingRequestDTO.java
  src/main/java/com/bytebreeze/quickdrop/security/SecurityConfig.java
  src/main/java/com/bytebreeze/quickdrop/service/ParcelService.java
  src/main/resources/templates/dashboard/book-parcel.html
Labels: enhancement, feature, Pull Request

#256 Feat/main sd 09 rider update status of assigned parcel delivery
  docs/Khairul/draft-code/draftCode.java
  docs/Khairul/draft-code/test.html
  docs/Khairul/draftCode.java
  src/main/java/com/bytebreeze/quickdrop/controller/RiderController.java
  src/main/java/com/bytebreeze/quickdrop/model/Parcel.java
  src/main/java/com/bytebreeze/quickdrop/repository/ParcelRepository.java
  src/main/java/com/bytebreeze/quickdrop/service/ParcelService.java
  src/main/java/com/bytebreeze/quickdrop/service/RiderService.java
  src/main/resources/application.properties
  src/main/resources/templates/rider/view-assigned-parcels.html
Labels: Pull Request
